### PR TITLE
Add support to Belkin B2B128 USB3 to Ethernet adapter

### PR DESCRIPTION
**Pull request by jdpc86**
Hi,

I updated 2 files based on what I read online, what I'm trying to do is to add support to a Belkin usb3 ethernet adapter, its vendor product id are 050d and 0128.

chipset based on my knowledge is ASIX AX88179...

please review...

Thanks!

### CODE REVIEW

**Comment by rbgarga** [comment]
We need to hear from @loos-br but I believe the right way is to submit this change to FreeBSD first and then, when it's accepted there, we can cherry-pick it

**Comment by jdpc86** [comment]
Thanks for your comment!
I tried this on OPNSense 20.1.7 with a local build of kernel...it didn't appear to have worked though...perhaps missing something still...this is a usb hub/ethernet combo...

hmm spoken too soon, it appears to work after:
kldload if_cdce
kldload if_axge
running devd -d to check message...
ue0 showed up with the right mac address...

**Comment by jdpc86** [comment]
...created a PR on FreeBSD as well:

https://github.com/freebsd/freebsd/pull/439

**Comment by jdpc86** [comment]
...closing this PR as it's going into upstream freebsd 12.1 where this is tested with OPNSense 20.7 20.7.2.
while the device was recognized with freebsd 11.2 that OPNSense 20.1 was based on...it is 'malfunctioning' in that it can get ip address, but there appears to be some issue on PHY/data link layer...couldn't get IP address via dhcp, tcpdump indicates that it has invalid EtherType, oui Unknown errs etc.

**Pull request closed without merging**
