### PR TITLE
Option 77 Additions to dhclient

### PR DESCRIPTION
**Pull request by marjohn56**
These changes were present in the dhclient used in pfSense 2.3, they
seem not to have made it into FreeBSD 11  as used in  pfSense 2..4

I have merely taken the changes and applied them to the FreeBSD 11
dhclient. Users who require this have tested it and confirm it is
working fine.

### CODE REVIEW

**Comment by rbgarga** [comment]
@marjohn56 we didn't change dhclient on 2.3 and 2.4, we are using FreeBSD stock. If you found a bug in dhclient on FreeBSD, we should report it there and get it fixed there.

Other than that, this branch (devel) is based on FreeBSD stable/10. The branch used to build 2.4 is RELENG_2_4, which is based in FreeBSD 11.0 (releng/11.0).

It would be good to have more information regarding the bug (what happens, steps to reproduce) then we can check if it's reproducible on FreeBSD 12.0-CURRENT and 11.0-STABLE

**Comment by marjohn56** [comment]
Can I refer you to these threads.

https://forum.pfsense.org/index.php?topic=116487.msg702439#msg702439

https://forum.pfsense.org/index.php?topic=127324.0

**Comment by rbgarga** [comment]
@marjohn56 I'm just trying to understand. Where did you get these changes from? I've checked all pfSense branches and also the old pfSense-tools repository and didn't find any patch changing any file inside sbin/dhclient.

I've also checked FreeBSD repository, branch master, and sbin/dhclient/bpf.c is not changed since 2014 as you can see in

https://github.com/freebsd/freebsd/commits/master/sbin/dhclient/bpf.c

**Comment by marjohn56** [comment]
:) I was sent them by one of my testers, he has a place in France so needs these changes. I'll ask him to jump in here and give some input. I find it strange that one of the posters in those threads I listed says that it did work in 2.3 though. I'll email him now, see if he can shine a light on this.

**Comment by nivek1612** [comment]
So here is the low down
Orange FTTH requires that dhclient send option 77 on a dhcp request. The stock 2.3 dhclient does not do this and fails to send option 77

In addition Orange also requires, depending on the region in France, that the dhcp request packet is tagged with priority (802.1q) as specified in the .conf file. Note only the dhcp request must use the priority. If all packets are tagged via he pfsense GUI VLAN settings priority option flow is reduced significantly.

I found a poster on a French forum who had managed to change dhclient to achieve these two requirements. I tested this at 2.3 and it worked correctly and allowed me to obtain an IP address.

As this was effectively a binary from a forum I was keen to get the diff file from the author to ensure the binary I was using was clean. Once I had this I asked Martin to rework the changes at 2.4

I will hunt out the forum posts later today as I'm travelling at the moment

**Comment by marjohn56** [comment]
My mis-interpretation then. 'fred' posted on the forum that it worked in 2.3, when in fact it was not part of the FreeBSD dhclient but a third party change.

Not a bug, but an addition.

**Comment by rbgarga** [comment]
IMO it should be sent to FreeBSD. What do you think @loos-br ?

**Comment by fredlubrano** [comment]
HI,

view the post https://lafibre.info/remplacer-livebox/remplacer-sa-livebox-par-un-routeur-pfsense/msg412567/#msg412567 and view diff dhclient_orange.txt


[dhclient_orange.txt](https://github.com/pfsense/FreeBSD-src/files/880373/dhclient_orange.txt)

**Comment by fredlubrano** [comment]
View default dhclient, not possible send option 77 and 90 for authification Orange :

[2.4.0-BETA][admin@jr.xxxx.io]/root: tcpdump -nni vmx0_vlan832 -s0 -vvv
tcpdump: listening on vmx0_vlan832, link-type EN10MB (Ethernet), capture size 262144 bytes
10:58:33.327719 IP (tos 0x10, ttl 128, id 0, offset 0, flags [none], proto UDP (17), length 328)
    0.0.0.0.68 > 255.255.255.255.67: [udp sum ok] BOOTP/DHCP, Request from 00:0c:29:5c:ac:dc, length 300, xid 0x929f61ef, secs 12, Flags [none] (0x0000)
          Client-Ethernet-Address 00:0c:29:5c:ac:dc
          Vendor-rfc1048 Extensions
            Magic Cookie 0x63825363
            DHCP-Message Option 53, length 1: Discover
            Vendor-Class Option 60, length 5: "sagem"
            Client-ID Option 61, length 7: ether 00:0c:29:5c:ac:dc
            Hostname Option 12, length 2: "jr"
            END Option 255, length 0

The client dhclient, possible send option 77 and 90 for authification Orange :

[2.4.0-BETA][admin@jr.xxxx.io]/root: tcpdump -nni vmx0_vlan832 -s0 -vvv
tcpdump: listening on vmx0_vlan832, link-type EN10MB (Ethernet), capture size 262144 bytes
11:00:17.456075 IP (tos 0x10, ttl 128, id 0, offset 0, flags [none], proto UDP (17), length 373)
    0.0.0.0.68 > 255.255.255.255.67: [udp sum ok] BOOTP/DHCP, Request from 00:0c:29:5c:ac:dc, length 345, xid 0x27ff3083, Flags [none] (0x0000)
          Client-Ethernet-Address 00:0c:29:5c:ac:dc
          Vendor-rfc1048 Extensions
            Magic Cookie 0x63825363
            DHCP-Message Option 53, length 1: Discover
            Vendor-Class Option 60, length 5: "sagem"
            Client-ID Option 61, length 7: ether 00:0c:29:5c:ac:dc
            User-Class Option 77, length 44:
              instance#1: "FSVDSL_livebox.Internet.softathome.Livebox4", length 43
            AUTH Option 90, length 22: 0.0.0.0.0.0.0.0.0.0.0.102.116.105.47.100.98.101.xx.xxx.xx.xx
            Hostname Option 12, length 2: "jr"
            Parameter-Request Option 55, length 9:
              Subnet-Mask, BR, Lease-Time, RN
              RB, Option 119, Default-Gateway, Domain-Name-Server
              AUTH
            END Option 255, length 0

View post forum "https://lafibre.info" https://lafibre.info/remplacer-livebox/remplacer-sa-livebox-par-un-routeur-pfsense/msg412567/#msg412567
View https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=184117

**Comment by marjohn56** [comment]
@loos-br 
@rbgarga 

Thoughts please, PR this upstream? It seems from freds comments on bugzilla this was attempted in the past, but the PR that was used did not contain all of the changes required to make it work, From what fred and kev are saying this does indeed sort the problem they are having.

**Comment by dani** [comment]
There are at least 2 different issues here (I'm also using pfsense to replace my ISP router, which is the same as the OP: Orange, in France)

The first thing, which is clearly a bug in the DHCP client is the lack of support for Option 77, and should be fixed by appying the patch from here https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=184117. Looks like the patch has been applied upstream (see https://svnweb.freebsd.org/base/head/sbin/dhclient/tables.c) but is not (yet ?) in pfsense RELENG_2_4 branch. Can this be backported ?

The other problem is a new feature request, for sending requests using a specific 802.1q priority. Not sure if this is better upstream or maintained in PfSense as it's quite specific. But I'm interested in having it supported in PfSense too ;-) (for now, I'm altering the priority using an external switch as I'm lucky enough to have such an hardware)

**Comment by rbgarga** [comment]
@dani you are right, https://svnweb.freebsd.org/base?view=revision&revision=306053 was never MFC'd to stable/11 so it never reached pfSense 2.4. We can backport it without problems IMO. thoughts @loos-br ?

Regarding the feature request of adding 802.1q priority support to dhclient, IMO it should be send to FreeBSD under https://reviews.freebsd.org to make it possible to have more developers attention and review. And of course we can work together to get it committed on FreeBSD and also on pfSense

**Comment by HanXHX** [comment]
any news about this PR?

**Comment by olivierlambert** [comment]
Hi there, waiting for this PR to be merged :+1: 
Keep up the good work!

**Comment by loos-br** [comment]
I did the MFC of https://svnweb.freebsd.org/base?view=revision&revision=306053, but this patch still needs a review.

**Comment by loos-br** [comment]
Option 77 is confirmed to work now (without this patch), I'm looking to see what we can do about the VLAN priority.

**Pull request closed without merging**
