### PR TITLE
6RD Changes from 2.4

### PR DESCRIPTION
**Pull request by rschell**
Collected from changes applied to 2.4 in August 3-22, 2017
Potential fix for #9561 and #9649

### CODE REVIEW

**Comment by rbgarga** [comment]
@loos-br can you take a look at this one?

**Review by rschell — COMMENTED** [review]
Finally was able to build a test version with commits through 9-3 or so on all three gits (pfSense, FreeBSD-src & FreeBSD-ports), the WAN connection displays an IPv6 Address now on the dashboard where it did not prior.  ifconfig no longer returns a "1" exit code in connecting the wan_stf interface.  "test-ipv6" reports 10/10 now, where ipv6 was failing before.

**Review by rschell — COMMENTED** [review]
When applying the if_stf.c changes to releng/12.1, there is a "IN_IFADDR_RLOCK(&in_ifa_tracker);" that inadvertently gets deleted that should remain.  The code block starting at old line #377 should look like:

	CK_STAILQ_FOREACH(ia, &ifp->if_addrhead, ifa_link) {
		if (ia->ifa_addr->sa_family != AF_INET6)
			continue;
		ia6 = (struct in6_ifaddr *)ia;
		*&addr6 = ((struct sockaddr_in6 *)ia->ifa_addr)->sin6_addr;
		*&mask6 = ia6->ia_prefixmask.sin6_addr;
		if (sc->srcv4_addr != INADDR_ANY)
			bcopy(&sc->srcv4_addr, &in, sizeof(in));
		else {
			if (stf_getin4addr(sc, &sin4, addr6, mask6) == NULL)
				continue;
			bcopy(&sin4.sin_addr, &in, sizeof(in));
		}
		IN_IFADDR_RLOCK(&in_ifa_tracker);
		LIST_FOREACH(ia4, INADDR_HASH(in.s_addr), ia_hash)
			if (ia4->ia_addr.sin_addr.s_addr == in.s_addr)
				break;
		IN_IFADDR_RUNLOCK(&in_ifa_tracker);
		if (ia4 == NULL)
			continue;

		*addr = addr6;
		*mask = mask6;
		if_addr_runlock(ifp);
		return (0);

This snippet is without the STF_DEBUG code included.

**Comment by rschell** [comment]
For the record, I have been using this patch since its submission to get a functioning 6rd tunnel.  Without it, my 6rd tunnel does not work and I just check my 6/17 against the 6/17 Netgate snapshot.  Are there other plans get 6rd working?

**Pull request closed without merging**
